// Auto-generated by ggen --- DO NOT EDIT
// Source: ggen/ontology/gymact/profile.ttl (urn:gymact:scheme:consequence),
// via ggen/queries/extract-gymact-consequence.rq and this template.
// To change this file, edit the vendored ontology and re-run `ggen sync`.

//! GymAct consequence classes — a Rust projection of `urn:gymact:scheme:consequence`.
//!
//! Each variant corresponds to one `skos:Concept` in the vendored GymAct profile.
//! Doc comments below are the concepts' own `skos:definition` text, carried
//! verbatim from the admitted ontology.

/// GymAct's `urn:gymact:scheme:consequence` classification of a capability.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ConsequenceClass {
    /// Consequential capability whose execution is represented by SOSA actuation semantics and requires an admitted external authority decision when the environment declares authority required.
    Do,
    /// Observation-only capability; represented by SOSA observation semantics and never itself a consequential DO.
    Read,
}

impl ConsequenceClass {
    /// Whether this consequence class, per its own ontology definition,
    /// requires an admitted external authority decision before exercise.
    ///
    /// Structure only: this reflects the *declared* semantics of the concept
    /// (see each variant's doc comment); it never itself performs or checks
    /// authorization. Pair with `wasm4pm_compat::authority::AuthorityEnvelope`.
    #[must_use]
    pub const fn requires_authority(self) -> bool {
        match self {
            ConsequenceClass::Do => true,
            ConsequenceClass::Read => false,
        }
    }
}
