import { z } from 'zod';

// Auto-generated by ggen --- DO NOT EDIT
// Source: zod-types.ttl




  
    
export const ArcSchema = z.object({
    
  
  "from": z.string(),

  
  "to": z.string(),

  
  "weight": z.number().optional(),

  
    
});

export type Arc = z.infer<typeof ArcSchema>;

    
export const BpmnEdgeSchema = z.object({
    
  
  "id": z.string(),

  
  "source": z.string(),

  
  "target": z.string(),

  
    
});

export type BpmnEdge = z.infer<typeof BpmnEdgeSchema>;

    
export const BpmnLaneSchema = z.object({
    
  
  "id": z.string(),

  
  "name": z.string(),

  
  "nodes": z.array(z.string()),

  
    
});

export type BpmnLane = z.infer<typeof BpmnLaneSchema>;

    
export const BpmnNodeSchema = z.object({
    
  
  "id": z.string(),

  
  "kind": z.string(),

  
  "name": z.string().optional(),

  
    
});

export type BpmnNode = z.infer<typeof BpmnNodeSchema>;

    
export const BpmnProcessSchema = z.object({
    
  
  "edges": z.array(z.lazy(() => BpmnEdgeSchema)),

  
  "lanes": z.array(z.lazy(() => BpmnLaneSchema)),

  
  "nodes": z.array(z.lazy(() => BpmnNodeSchema)),

  
    
});

export type BpmnProcess = z.infer<typeof BpmnProcessSchema>;

    
export const CompatDiagnosticSchema = z.object({
    
  
  "message": z.string(),

  
  "severity": z.string(),

  
  "variant": z.string(),

  
    
});

export type CompatDiagnostic = z.infer<typeof CompatDiagnosticSchema>;

    
export const ConformanceResultSchema = z.object({
    
  
  "deviating_traces": z.number(),

  
  "fitness": z.number(),

  
  "fitting_traces": z.number(),

  
  "precision": z.number().optional(),

  
  "total_traces": z.number(),

  
    
});

export type ConformanceResult = z.infer<typeof ConformanceResultSchema>;

    
export const ConformanceVerdictSchema = z.object({
    
  
  "is_perfect": z.boolean(),

  
    
});

export type ConformanceVerdict = z.infer<typeof ConformanceVerdictSchema>;

    
export const DFGSchema = z.object({
    
  
  "edges": z.array(z.lazy(() => DFGEdgeSchema)),

  
  "nodes": z.array(z.lazy(() => DFGNodeSchema)),

  
    
});

export type DFG = z.infer<typeof DFGSchema>;

    
export const DFGEdgeSchema = z.object({
    
  
  "frequency": z.number(),

  
  "source": z.string(),

  
  "target": z.string(),

  
    
});

export type DFGEdge = z.infer<typeof DFGEdgeSchema>;

    
export const DFGNodeSchema = z.object({
    
  
  "activity": z.string(),

  
  "frequency": z.number(),

  
    
});

export type DFGNode = z.infer<typeof DFGNodeSchema>;

    
export const DeclareConstraintSchema = z.object({
    
  
  "activities": z.array(z.string()),

  
  "constraint_type": z.string(),

  
    
});

export type DeclareConstraint = z.infer<typeof DeclareConstraintSchema>;

    
export const DeclareModelSchema = z.object({
    
  
  "constraints": z.array(z.lazy(() => DeclareConstraintSchema)),

  
    
});

export type DeclareModel = z.infer<typeof DeclareModelSchema>;

    
export const DiagnosticSeveritySchema = z.object({
    
  
  "Error": z.string(),

  
  "Info": z.string(),

  
  "Warning": z.string(),

  
    
});

export type DiagnosticSeverity = z.infer<typeof DiagnosticSeveritySchema>;

    
export const EventSchema = z.object({
    
  
  "activity": z.string(),

  
  "lifecycle": z.string().optional(),

  
  "resource": z.string().optional(),

  
  "timestamp_ns": z.number().optional(),

  
    
});

export type Event = z.infer<typeof EventSchema>;

    
export const EventLogSchema = z.object({
    
  
  "attributes": z.record(z.string(), z.string()),

  
  "traces": z.array(z.lazy(() => TraceSchema)),

  
    
});

export type EventLog = z.infer<typeof EventLogSchema>;

    
export const EvidenceSchema = z.object({
    
  
  "inner": z.any(),

  
  "state": z.lazy(() => EvidenceStateSchema),

  
  "witness": z.string(),

  
    
});

export type Evidence = z.infer<typeof EvidenceSchema>;

    
export const EvidenceStateSchema = z.object({
    
  
  "Admitted": z.string(),

  
  "Exportable": z.string(),

  
  "Projected": z.string(),

  
  "Raw": z.string(),

  
  "Receipted": z.string(),

  
  "Refused": z.string(),

  
    
});

export type EvidenceState = z.infer<typeof EvidenceStateSchema>;

    
export const LossChainSchema = z.object({
    
  
  "steps": z.array(z.lazy(() => NamedLossSchema)),

  
    
});

export type LossChain = z.infer<typeof LossChainSchema>;

    
export const LossReportSchema = z.object({
    
  
  "lost": z.any(),

  
  "policy": z.string(),

  
  "projection": z.string(),

  
    
});

export type LossReport = z.infer<typeof LossReportSchema>;

    
export const NamedLossSchema = z.object({
    
  
  "category": z.string(),

  
  "projection": z.string(),

  
    
});

export type NamedLoss = z.infer<typeof NamedLossSchema>;

    
export const ObjectTypeCardinalitySchema = z.object({
    
  
  "max_occurrence": z.number().optional(),

  
  "min_occurrence": z.number(),

  
  "object_type": z.string(),

  
    
});

export type ObjectTypeCardinality = z.infer<typeof ObjectTypeCardinalitySchema>;

    
export const OcelAttributeValueSchema = z.object({
    
  
  "Boolean": z.boolean().optional(),

  
  "Float": z.number().optional(),

  
  "Integer": z.number().optional(),

  
  "String": z.string().optional(),

  
    
});

export type OcelAttributeValue = z.infer<typeof OcelAttributeValueSchema>;

    
export const OcelEventSchema = z.object({
    
  
  "attributes": z.array(z.lazy(() => OcelEventAttributeSchema)),

  
  "id": z.string(),

  
  "relationships": z.array(z.lazy(() => OcelRelationshipSchema)),

  
  "time": z.number(),

  
  "type": z.string(),

  
    
});

export type OcelEvent = z.infer<typeof OcelEventSchema>;

    
export const OcelEventAttributeSchema = z.object({
    
  
  "name": z.string(),

  
  "value": z.lazy(() => OcelAttributeValueSchema),

  
    
});

export type OcelEventAttribute = z.infer<typeof OcelEventAttributeSchema>;

    
export const OcelLogSchema = z.object({
    
  
  "eventTypes": z.array(z.lazy(() => OcelTypeSchema)),

  
  "events": z.array(z.lazy(() => OcelEventSchema)),

  
  "objectTypes": z.array(z.lazy(() => OcelTypeSchema)),

  
  "objects": z.array(z.lazy(() => OcelObjectSchema)),

  
    
});

export type OcelLog = z.infer<typeof OcelLogSchema>;

    
export const OcelObjectSchema = z.object({
    
  
  "attributes": z.array(z.lazy(() => OcelObjectAttributeSchema)),

  
  "id": z.string(),

  
  "type": z.string(),

  
    
});

export type OcelObject = z.infer<typeof OcelObjectSchema>;

    
export const OcelObjectAttributeSchema = z.object({
    
  
  "name": z.string(),

  
  "time": z.number(),

  
  "value": z.lazy(() => OcelAttributeValueSchema),

  
    
});

export type OcelObjectAttribute = z.infer<typeof OcelObjectAttributeSchema>;

    
export const OcelRelationshipSchema = z.object({
    
  
  "objectId": z.string(),

  
  "qualifier": z.string(),

  
    
});

export type OcelRelationship = z.infer<typeof OcelRelationshipSchema>;

    
export const OcelTypeSchema = z.object({
    
  
  "attributes": z.array(z.lazy(() => OcelTypeAttributeSchema)),

  
  "name": z.string(),

  
    
});

export type OcelType = z.infer<typeof OcelTypeSchema>;

    
export const OcelTypeAttributeSchema = z.object({
    
  
  "name": z.string(),

  
  "type": z.string(),

  
    
});

export type OcelTypeAttribute = z.infer<typeof OcelTypeAttributeSchema>;

    
export const OrderEdgeSchema = z.object({
    
  
  "from": z.number(),

  
  "to": z.number(),

  
    
});

export type OrderEdge = z.infer<typeof OrderEdgeSchema>;

    
export const PetriNetSchema = z.object({
    
  
  "arcs": z.array(z.lazy(() => ArcSchema)),

  
  "places": z.array(z.lazy(() => PlaceSchema)),

  
  "transitions": z.array(z.lazy(() => TransitionSchema)),

  
    
});

export type PetriNet = z.infer<typeof PetriNetSchema>;

    
export const PlaceSchema = z.object({
    
  
  "id": z.string(),

  
  "name": z.string().optional(),

  
    
});

export type Place = z.infer<typeof PlaceSchema>;

    
export const PowlSchema = z.object({
    
  
  "edges": z.array(z.lazy(() => OrderEdgeSchema)),

  
  "nodes": z.array(z.lazy(() => PowlNodeSchema)),

  
  "root": z.number().optional(),

  
    
});

export type Powl = z.infer<typeof PowlSchema>;

    
export const PowlNodeSchema = z.object({
    
  
  "id": z.number(),

  
  "kind": z.string(),

  
    
});

export type PowlNode = z.infer<typeof PowlNodeSchema>;

    
export const ProcessPerspectiveSchema = z.object({
    
  
  "control-flow": z.string(),

  
  "data": z.string(),

  
  "resource": z.string(),

  
  "time": z.string(),

  
    
});

export type ProcessPerspective = z.infer<typeof ProcessPerspectiveSchema>;

    
export const ProcessTreeSchema = z.object({
    
  
  "nodes": z.array(z.lazy(() => ProcessTreeNodeSchema)),

  
  "root": z.number().optional(),

  
    
});

export type ProcessTree = z.infer<typeof ProcessTreeSchema>;

    
export const ProcessTreeNodeSchema = z.object({
    
  
  "children": z.array(z.number()),

  
  "kind": z.string(),

  
  "label": z.string().optional(),

  
    
});

export type ProcessTreeNode = z.infer<typeof ProcessTreeNodeSchema>;

    
export const ReceiptSchema = z.object({
    
  
  "final_hash_chain": z.string(),

  
  "model_id": z.string(),

  
  "verdict": z.lazy(() => ConformanceVerdictSchema),

  
    
});

export type Receipt = z.infer<typeof ReceiptSchema>;

    
export const TemporalOrderSchema = z.object({
    
  
  "after": z.string(),

  
  "before": z.string(),

  
  "concurrent": z.string(),

  
  "unknown": z.string(),

  
    
});

export type TemporalOrder = z.infer<typeof TemporalOrderSchema>;

    
export const TokenReplayResultSchema = z.object({
    
  
  "consumed_tokens": z.number(),

  
  "fitness": z.number(),

  
  "missing_tokens": z.number(),

  
  "produced_tokens": z.number(),

  
  "remaining_tokens": z.number(),

  
    
});

export type TokenReplayResult = z.infer<typeof TokenReplayResultSchema>;

    
export const TraceSchema = z.object({
    
  
  "events": z.array(z.lazy(() => EventSchema)),

  
  "id": z.string(),

  
    
});

export type Trace = z.infer<typeof TraceSchema>;

    
export const TransitionSchema = z.object({
    
  
  "id": z.string(),

  
  "label": z.string().optional(),

  
    
});

export type Transition = z.infer<typeof TransitionSchema>;

    
export const XesEventSchema = z.object({
    
  
  "attributes": z.record(z.string(), z.string()),

  
    
});

export type XesEvent = z.infer<typeof XesEventSchema>;

    
export const XesExtensionSchema = z.object({
    
  
  "name": z.string(),

  
  "prefix": z.string(),

  
  "uri": z.string(),

  
    
});

export type XesExtension = z.infer<typeof XesExtensionSchema>;

    
export const XesLifecycleTransitionSchema = z.object({
    
  
  "abort": z.string(),

  
  "assign": z.string(),

  
  "autoskip": z.string(),

  
  "complete": z.string(),

  
  "inprogress": z.string(),

  
  "manualskip": z.string(),

  
  "plan": z.string(),

  
  "reassign": z.string(),

  
  "resume": z.string(),

  
  "schedule": z.string(),

  
  "start": z.string(),

  
  "suspend": z.string(),

  
  "unknown": z.string(),

  
  "withdraw": z.string(),

  
    
});

export type XesLifecycleTransition = z.infer<typeof XesLifecycleTransitionSchema>;

    
export const XesLogSchema = z.object({
    
  
  "extensions": z.array(z.lazy(() => XesExtensionSchema)),

  
  "name": z.string(),

  
  "traces": z.array(z.lazy(() => XesTraceSchema)),

  
    
});

export type XesLog = z.infer<typeof XesLogSchema>;

    
export const XesTraceSchema = z.object({
    
  
  "events": z.array(z.lazy(() => XesEventSchema)),

  
  "name": z.string(),

});

export type XesTrace = z.infer<typeof XesTraceSchema>;
