use syn::visit::Visit;
use syn::{Expr, FnArg, ItemUse, Local, Pat, Signature, Type, UseTree};

/// Severity level for LSP diagnostics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum DiagnosticSeverity {
    Error,
    Warning,
    Info,
}

impl core::fmt::Display for DiagnosticSeverity {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            DiagnosticSeverity::Error => f.write_str("Error"),
            DiagnosticSeverity::Warning => f.write_str("Warning"),
            DiagnosticSeverity::Info => f.write_str("Info"),
        }
    }
}

/// An LSP diagnostic report generated by the checker.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct LspDiagnostic {
    pub rule_id: &'static str,
    pub severity: DiagnosticSeverity,
    pub message: String,
    pub line: usize,
    pub column: usize,
}

struct WitnessVisitor {
    diagnostics: Vec<LspDiagnostic>,
}

impl<'ast> Visit<'ast> for WitnessVisitor {
    fn visit_item_use(&mut self, node: &'ast ItemUse) {
        let (line, col) = get_span_start(&node.tree);
        check_use_tree(&node.tree, "", &mut self.diagnostics, line, col);
        syn::visit::visit_item_use(self, node);
    }

    fn visit_signature(&mut self, node: &'ast Signature) {
        // 1. Check function name for local solver/replay implementations (W4PM-ENG-02)
        let name_lower = node.ident.to_string().to_lowercase();
        let prohibited_funcs = [
            "align",
            "alignment",
            "replay",
            "token_replay",
            "state_space",
            "discover_model",
            "inductive_miner",
            "alpha_miner",
            "evaluate_query",
        ];
        for f in &prohibited_funcs {
            if name_lower.contains(f) {
                let (line, col) = get_span_start(&node.ident);
                self.diagnostics.push(LspDiagnostic {
                    rule_id: "W4PM-ENG-02",
                    severity: DiagnosticSeverity::Warning,
                    message: format!(
                        "Function '{}' suggests local replay/solver implementation. Ensure execution is graduated to wasm4pm instead of running locally.",
                        node.ident
                    ),
                    line,
                    column: col,
                });
            }
        }

        // 2. Check parameters for witness erasure (W4PM-WIT-01/02)
        for arg in &node.inputs {
            if let FnArg::Typed(pat_type) = arg {
                let param_name = get_pat_name(&pat_type.pat);
                if param_name.to_lowercase().contains("witness") {
                    if is_primitive_type(&pat_type.ty) {
                        let (line, col) = get_span_start(&pat_type.ty);
                        self.diagnostics.push(LspDiagnostic {
                            rule_id: "W4PM-WIT-01",
                            severity: DiagnosticSeverity::Error,
                            message: format!(
                                "Witness parameter '{}' is erased to primitive type. Use type-level witness markers.",
                                param_name
                            ),
                            line,
                            column: col,
                        });
                    }
                }
            }
        }

        syn::visit::visit_signature(self, node);
    }

    fn visit_field(&mut self, node: &'ast syn::Field) {
        if let Some(ident) = &node.ident {
            let field_name = ident.to_string();
            if field_name.to_lowercase().contains("witness") {
                if is_primitive_type(&node.ty) {
                    let (line, col) = get_span_start(&node.ty);
                    self.diagnostics.push(LspDiagnostic {
                        rule_id: "W4PM-WIT-01",
                        severity: DiagnosticSeverity::Error,
                        message: format!(
                            "Witness field '{}' is erased to a primitive type. Enforce type-level witness markers.",
                            field_name
                        ),
                        line,
                        column: col,
                    });
                }
            }
        }
        syn::visit::visit_field(self, node);
    }

    fn visit_local(&mut self, node: &'ast Local) {
        let var_name = get_pat_name(&node.pat);
        if var_name.to_lowercase().contains("witness") {
            let mut is_erased = false;
            if let Pat::Type(pat_type) = &node.pat {
                if is_primitive_type(&pat_type.ty) {
                    let (line, col) = get_span_start(&pat_type.ty);
                    self.diagnostics.push(LspDiagnostic {
                        rule_id: "W4PM-WIT-01",
                        severity: DiagnosticSeverity::Error,
                        message: format!(
                            "Local witness variable '{}' is annotated with a primitive type.",
                            var_name
                        ),
                        line,
                        column: col,
                    });
                    is_erased = true;
                }
            }
            if !is_erased {
                if let Some(init) = &node.init {
                    if is_expr_primitive_literal(&init.expr) {
                        let (line, col) = get_span_start(&init.expr);
                        self.diagnostics.push(LspDiagnostic {
                            rule_id: "W4PM-WIT-01",
                            severity: DiagnosticSeverity::Error,
                            message: format!(
                                "Local witness variable '{}' is assigned a primitive literal. Use type-level witness markers.",
                                var_name
                            ),
                            line,
                            column: col,
                        });
                    }
                }
            }
        }
        syn::visit::visit_local(self, node);
    }

    fn visit_type(&mut self, node: &'ast Type) {
        self.check_type_for_erased_generics(node);
        syn::visit::visit_type(self, node);
    }
}

impl WitnessVisitor {
    fn check_type_for_erased_generics(&mut self, ty: &Type) {
        if let Type::Path(type_path) = ty {
            for segment in &type_path.path.segments {
                let name = segment.ident.to_string();
                if name == "Admission" || name == "Evidence" || name == "Refusal" {
                    if let syn::PathArguments::AngleBracketed(args) = &segment.arguments {
                        if args.args.len() >= 2 {
                            if let syn::GenericArgument::Type(arg_ty) = &args.args[1] {
                                if is_primitive_type(arg_ty) {
                                    let (line, col) = get_span_start(arg_ty);
                                    self.diagnostics.push(LspDiagnostic {
                                        rule_id: "W4PM-WIT-03",
                                        severity: DiagnosticSeverity::Error,
                                        message: format!(
                                            "Generic witness parameter in '{}' is instantiated with primitive type. Use a type implementing Witness.",
                                            name
                                        ),
                                        line,
                                        column: col,
                                    });
                                }
                            }
                        }
                    }
                } else if name == "WitnessState" {
                    if let syn::PathArguments::AngleBracketed(args) = &segment.arguments {
                        if args.args.len() >= 1 {
                            if let syn::GenericArgument::Type(arg_ty) = &args.args[0] {
                                if is_primitive_type(arg_ty) {
                                    let (line, col) = get_span_start(arg_ty);
                                    self.diagnostics.push(LspDiagnostic {
                                        rule_id: "W4PM-WIT-03",
                                        severity: DiagnosticSeverity::Error,
                                        message: "Generic witness parameter in 'WitnessState' is instantiated with primitive type. Use a type implementing Witness.".to_string(),
                                        line,
                                        column: col,
                                    });
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn get_span_start<T: syn::spanned::Spanned>(node: &T) -> (usize, usize) {
    let span = node.span();
    let start = span.start();
    (start.line, start.column)
}

fn get_pat_name(pat: &Pat) -> String {
    match pat {
        Pat::Ident(pat_ident) => pat_ident.ident.to_string(),
        Pat::Type(pat_type) => get_pat_name(&pat_type.pat),
        Pat::Reference(pat_ref) => get_pat_name(&pat_ref.pat),
        _ => String::new(),
    }
}

fn is_primitive_type(ty: &Type) -> bool {
    match ty {
        Type::Path(type_path) => {
            if let Some(segment) = type_path.path.segments.last() {
                let name = segment.ident.to_string();
                matches!(
                    name.as_str(),
                    "bool"
                        | "String"
                        | "str"
                        | "char"
                        | "u8"
                        | "u16"
                        | "u32"
                        | "u64"
                        | "u128"
                        | "i8"
                        | "i16"
                        | "i32"
                        | "i64"
                        | "i128"
                )
            } else {
                false
            }
        }
        Type::Reference(type_ref) => is_primitive_type(&type_ref.elem),
        _ => false,
    }
}

fn is_expr_primitive_literal(expr: &Expr) -> bool {
    match expr {
        Expr::Lit(expr_lit) => {
            matches!(
                &expr_lit.lit,
                syn::Lit::Bool(_) | syn::Lit::Str(_) | syn::Lit::ByteStr(_) | syn::Lit::Char(_)
            )
        }
        _ => false,
    }
}

fn check_use_tree(
    tree: &UseTree,
    prefix: &str,
    diagnostics: &mut Vec<LspDiagnostic>,
    line: usize,
    col: usize,
) {
    match tree {
        UseTree::Path(use_path) => {
            let next_prefix = if prefix.is_empty() {
                use_path.ident.to_string()
            } else {
                format!("{}::{}", prefix, use_path.ident)
            };
            check_use_tree(&use_path.tree, &next_prefix, diagnostics, line, col);
        }
        UseTree::Name(use_name) => {
            let full_path = if prefix.is_empty() {
                use_name.ident.to_string()
            } else {
                format!("{}::{}", prefix, use_name.ident)
            };
            check_path_for_leakage(&full_path, diagnostics, line, col);
        }
        UseTree::Rename(use_rename) => {
            let full_path = if prefix.is_empty() {
                use_rename.ident.to_string()
            } else {
                format!("{}::{}", prefix, use_rename.ident)
            };
            check_path_for_leakage(&full_path, diagnostics, line, col);
        }
        UseTree::Glob(_) => {
            check_path_for_leakage(prefix, diagnostics, line, col);
        }
        UseTree::Group(use_group) => {
            for item in &use_group.items {
                check_use_tree(item, prefix, diagnostics, line, col);
            }
        }
    }
}

fn check_path_for_leakage(
    path: &str,
    diagnostics: &mut Vec<LspDiagnostic>,
    line: usize,
    col: usize,
) {
    let prohibited = [
        "pm4py",
        "pm4py_rs",
        "rust_process_mining",
        "rapid_pm",
        "wasm4pm_engine",
        "wasm4pm::engine",
        "z3",
        "egg",
        "cbc",
        "glpk",
        "lp_modeler",
        "minisat",
        "minilp",
        "good_lp",
        "coin_cbc",
        "rocksdb",
        "sled",
    ];

    for engine in &prohibited {
        if path == *engine || path.starts_with(&format!("{}::", engine)) {
            diagnostics.push(LspDiagnostic {
                rule_id: "W4PM-ENG-01",
                severity: DiagnosticSeverity::Error,
                message: format!(
                    "Prohibited import of solver/execution engine '{}' found. Compatibility layer must remain structure-only. Graduate to wasm4pm.",
                    engine
                ),
                line,
                column: col,
            });
            break;
        }
    }
}

/// Check the provided Rust source code for W4PM-WIT and W4PM-ENG rules.
pub fn check_source(source: &str) -> Vec<LspDiagnostic> {
    let file_res = syn::parse_file(source);
    match file_res {
        Ok(file) => {
            let mut visitor = WitnessVisitor {
                diagnostics: Vec::new(),
            };
            visitor.visit_file(&file);
            visitor.diagnostics
        }
        Err(err) => {
            let span = err.span();
            let start = span.start();
            vec![LspDiagnostic {
                rule_id: "SYNTAX-ERROR",
                severity: DiagnosticSeverity::Error,
                message: format!("Failed to parse source file: {}", err),
                line: start.line,
                column: start.column,
            }]
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_clean_code() {
        let code = r#"
            use wasm4pm_compat::witness::Ocel20;
            use wasm4pm_compat::admission::Admission;

            pub struct Claims<W: Witness> {
                pub witness: W,
            }

            pub fn verify_boundary<W: Witness>(admission: Admission<LogData, W>) {}
        "#;
        let diagnostics = check_source(code);
        assert!(
            diagnostics.is_empty(),
            "Expected zero diagnostics, got {:?}",
            diagnostics
        );
    }

    #[test]
    fn test_witness_erasure_bool_field() {
        let code = r#"
            pub struct Claims {
                pub has_ocel_witness: bool,
            }
        "#;
        let diagnostics = check_source(code);
        assert!(!diagnostics.is_empty());
        let d = &diagnostics[0];
        assert_eq!(d.rule_id, "W4PM-WIT-01");
        assert!(d
            .message
            .contains("Witness field 'has_ocel_witness' is erased"));
    }

    #[test]
    fn test_witness_erasure_string_param() {
        let code = r#"
            pub fn admit(data: Log, active_witness: String) {}
        "#;
        let diagnostics = check_source(code);
        assert!(!diagnostics.is_empty());
        let d = &diagnostics[0];
        assert_eq!(d.rule_id, "W4PM-WIT-01");
        assert!(d
            .message
            .contains("Witness parameter 'active_witness' is erased"));
    }

    #[test]
    fn test_witness_erasure_generic_args() {
        let code = r#"
            fn process() {
                let evidence: Admission<LogData, bool> = get_evidence();
            }
        "#;
        let diagnostics = check_source(code);
        assert!(!diagnostics.is_empty());
        let d = &diagnostics[0];
        assert_eq!(d.rule_id, "W4PM-WIT-03");
        assert!(d.message.contains(
            "Generic witness parameter in 'Admission' is instantiated with primitive type"
        ));
    }

    #[test]
    fn test_witness_erasure_witness_state_generic_args() {
        let code = r#"
            fn process() {
                let state: WitnessState<String> = get_state();
            }
        "#;
        let diagnostics = check_source(code);
        assert!(!diagnostics.is_empty());
        let d = &diagnostics[0];
        assert_eq!(d.rule_id, "W4PM-WIT-03");
        assert!(d.message.contains(
            "Generic witness parameter in 'WitnessState' is instantiated with primitive type"
        ));
    }

    #[test]
    fn test_witness_erasure_primitive_literal_assignment() {
        let code = r#"
            fn check() {
                let active_witness = true;
            }
        "#;
        let diagnostics = check_source(code);
        assert!(!diagnostics.is_empty());
        let d = &diagnostics[0];
        assert_eq!(d.rule_id, "W4PM-WIT-01");
        assert!(d
            .message
            .contains("Local witness variable 'active_witness' is assigned a primitive literal"));
    }

    #[test]
    fn test_engine_leakage_import() {
        let code = r#"
            use z3::Solver;
            use pm4py::replay;
        "#;
        let diagnostics = check_source(code);
        assert_eq!(diagnostics.len(), 2);
        assert_eq!(diagnostics[0].rule_id, "W4PM-ENG-01");
        assert_eq!(diagnostics[1].rule_id, "W4PM-ENG-01");
    }

    #[test]
    fn test_engine_leakage_local_impl() {
        let code = r#"
            pub fn run_token_replay_logic() {}
        "#;
        let diagnostics = check_source(code);
        assert!(!diagnostics.is_empty());
        let d = &diagnostics[0];
        assert_eq!(d.rule_id, "W4PM-ENG-02");
        assert!(d
            .message
            .contains("suggests local replay/solver implementation"));
    }
}
