PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX compat: <https://wasm4pm.dev/ns#>

SELECT ?breed_id ?fresh_name
WHERE {
  ?b a compat:CognitionBreed ;
     compat:breedId   ?breed_id ;
     compat:freshName ?fresh_name .
}
ORDER BY ?breed_id ?fresh_name
