#!/usr/bin/env bash
# audit-gap-decomposition.sh.tera: Decomposes git commit history against gap ledger.
# Constitutional Equation: audits/audit-gap-decomposition.sh = mu(gap-ledger.yaml, commit history, classification rules)
#
# Purpose:
#   1. Load gap ledger (gap-ledger.yaml) and parse gap IDs with closure conditions
#   2. Iterate over git log (commit hash, message, author, timestamp)
#   3. For each commit, classify as one of nine categories:
#       - GAP_CLOSURE:      Directly closes a documented gap
#       - AUDIT_MACHINERY:  Test fixture, audit script, or proof-gate infrastructure
#       - ONTOLOGY_LAW:     Refines the type-law ontology (src/law.rs, src/nightly_foundry.rs)
#       - QUERY_SURFACE:    SPARQL, RDF, or audit query definitions
#       - TEMPLATE_SURFACE: Tera templates, codegen, or manufacturing templates
#       - FIXTURE_RECEIPT:  Compile-fail/pass fixtures, trybuild receipts (ALIVE gate)
#       - CHECKPOINT:       Milestone commits (PAPERLAW_*, CROWN_*, ALIVE_* releases)
#       - AUXILIARY:        Explicitly supporting another commit's closure
#       - UNMAPPED:         No clear classification found
#
# Validation Rules:
#   - PASS: 0 critical gaps unmapped (all HIGH/CRITICAL gaps have closures)
#   - PASS: 0 ALIVE claims made from commit count alone (ALIVE status must cite gap_id)
#   - PASS: 0 uncited closure claims (every GAP_CLOSURE commit must reference a gap_id)
#   - PASS: auxiliary commits explicitly classified (no hidden debt)
#
# Return Codes:
#   0 — All validation rules pass; gap decomposition is sound
#   1 — Critical validation failure (uncited closure, unmapped critical gap, etc.)
#
# Input Variables (from ggen):
#   gapLedgerPath      — path to gap-ledger.yaml (typically: ggen/emitted/gap-ledger.yaml)
#   commitStartRef     — git ref for range start (typically: origin/main)
#   commitEndRef       — git ref for range end (typically: HEAD)
#   classificationRules — path to classification rules (if provided)
#
# Output Files:
#   emitted/audits/audit-gap-decomposition.sh — this executable script
#   (stdout) — audit log with per-commit classification and pass/fail summary
#
# Auto-generated by ggen from gap-ledger.yaml --- DO NOT EDIT
# Source: ggen/emitted/gap-ledger.yaml
# Regenerate with: ggen sync --template audit-gap-decomposition.sh.tera

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
AUDIT_OUTDIR="${REPO_ROOT}/ggen/audits"
LEDGER_PATH="${1:-ggen/emitted/gap-ledger.yaml}"
COMMIT_START="${2:-origin/main}"
COMMIT_END="${3:-HEAD}"

# Counters and tracking
PASS_COUNT=0
FAIL_COUNT=0
declare -A GAP_ID_TO_STATUS
declare -A COMMIT_CLASSIFICATION
declare -A CLOSURE_CLAIMS_UNCITED
CRITICAL_GAPS_UNMAPPED=()
AUDIT_ISSUES=()

pass() { echo "PASS  $1"; (( PASS_COUNT += 1 )); }
fail() { echo "FAIL  $1"; (( FAIL_COUNT += 1 )); }
warn() { echo "WARN  $1"; }
info() { echo "INFO  $1"; }

# =========================================================================
# PHASE 1: Load Gap Ledger
# =========================================================================

info "Phase 1: Loading gap ledger from ${LEDGER_PATH}"

if [[ ! -f "${REPO_ROOT}/${LEDGER_PATH}" ]]; then
    fail "gap-ledger-exists: ${LEDGER_PATH} not found"
    exit 1
fi

# Parse gap IDs and severity from YAML
# Expected structure:
#   gaps:
#     - id: GAP_001
#       gap_severity: HIGH
#       status: MANUFACTURED
#       changed_files: [...]

declare -a ALL_GAP_IDS
declare -A GAP_SEVERITY
declare -A GAP_STATUS

while IFS= read -r line; do
    if [[ "$line" =~ ^[[:space:]]*-[[:space:]]*id:[[:space:]]*(GAP_[A-Z0-9_]+) ]]; then
        gap_id="${BASH_REMATCH[1]}"
        ALL_GAP_IDS+=("$gap_id")
    elif [[ "$line" =~ gap_severity:[[:space:]]*(CRITICAL|HIGH|MEDIUM|LOW) ]]; then
        severity="${BASH_REMATCH[1]}"
        GAP_SEVERITY["${ALL_GAP_IDS[-1]}"]="$severity"
    elif [[ "$line" =~ ^[[:space:]]*status:[[:space:]]*(MANUFACTURED|OPEN|PARTIAL) ]]; then
        status="${BASH_REMATCH[1]}"
        GAP_STATUS["${ALL_GAP_IDS[-1]}"]="$status"
    fi
done < <(grep -E "id:|gap_severity:|status:" "${REPO_ROOT}/${LEDGER_PATH}")

pass "gap-ledger-loaded: ${#ALL_GAP_IDS[@]} gaps loaded"

for gap_id in "${ALL_GAP_IDS[@]}"; do
    info "  - ${gap_id} (${GAP_SEVERITY[$gap_id]:-UNKNOWN} / ${GAP_STATUS[$gap_id]:-UNKNOWN})"
done

# =========================================================================
# PHASE 2: Iterate Git Log and Classify Commits
# =========================================================================

info ""
info "Phase 2: Classifying commits in range ${COMMIT_START}..${COMMIT_END}"

declare -a UNCLASSIFIED_COMMITS=()
declare -a GIT_COMMIT_LOG=()

# Pre-fetch git log to avoid subprocess scope issues
while IFS='|' read -r line; do
    GIT_COMMIT_LOG+=("$line")
done < <(git log --pretty=format:"%H|%s|%an|%ai|%P" "${COMMIT_START}..${COMMIT_END}" 2>/dev/null || true)

for commit_line in "${GIT_COMMIT_LOG[@]}"; do
    IFS='|' read -r hash subject author timestamp parents <<<"$commit_line"
    classification="UNMAPPED"
    cited_gap_id=""

    # Strip leading/trailing whitespace from subject
    subject=$(echo "$subject" | xargs)

    # =====================================================================
    # Classification Rules
    # =====================================================================

    # Rule 1: Gap Closure — commit message contains gap_id (GAP_*)
    if [[ "$subject" =~ GAP_[A-Z0-9_]+ ]]; then
        cited_gap_id="${BASH_REMATCH[0]}"
        # Verify gap_id exists in ledger
        if [[ " ${ALL_GAP_IDS[*]} " =~ " ${cited_gap_id} " ]]; then
            classification="GAP_CLOSURE"
            CLOSURE_CLAIMS_UNCITED["${hash}"]="${cited_gap_id}"
        else
            fail "gap-closure-invalid: commit ${hash} cites nonexistent ${cited_gap_id}"
        fi
    fi

    # Rule 2: Fixture/Receipt — contains fixture, compile-fail, compile-pass, ui/
    if [[ "$subject" =~ (fixture|compile-fail|compile-pass|ui|trybuild) ]]; then
        if [[ "$classification" == "UNMAPPED" ]]; then
            classification="FIXTURE_RECEIPT"
        fi
    fi

    # Rule 3: Audit Machinery — contains audit, test, proof-gate
    if [[ "$subject" =~ (audit|proof-gate|validation|gate) ]] && [[ "$classification" == "UNMAPPED" ]]; then
        classification="AUDIT_MACHINERY"
    fi

    # Rule 4: Ontology Law — touches src/law.rs, src/nightly_foundry.rs, witness, state
    if git show --name-only "${hash}" 2>/dev/null | grep -qE "src/(law|nightly_foundry|witness|state|evidence|admission)\.rs"; then
        if [[ "$classification" == "UNMAPPED" ]]; then
            classification="ONTOLOGY_LAW"
        fi
    fi

    # Rule 5: Query Surface — touches ggen/queries/*.rq, SPARQL, RDF
    if git show --name-only "${hash}" 2>/dev/null | grep -qE "(ggen/queries|\.rq|sparql|rdf)"; then
        if [[ "$classification" == "UNMAPPED" ]]; then
            classification="QUERY_SURFACE"
        fi
    fi

    # Rule 6: Template Surface — touches ggen/templates/*.tera or codegen
    if git show --name-only "${hash}" 2>/dev/null | grep -qE "ggen/templates|\.tera|codegen"; then
        if [[ "$classification" == "UNMAPPED" ]]; then
            classification="TEMPLATE_SURFACE"
        fi
    fi

    # Rule 7: Checkpoint — commit message matches release/milestone pattern
    if [[ "$subject" =~ ^(PAPERLAW|CROWN|ALIVE|NIGHTLY|RELEASE)_ ]]; then
        if [[ "$classification" == "UNMAPPED" ]]; then
            classification="CHECKPOINT"
        fi
    fi

    # Rule 8: Auxiliary — explicitly marked or supports another commit
    if [[ "$subject" =~ (auxiliary|support|infrastructure|prep|setup) ]]; then
        if [[ "$classification" == "UNMAPPED" ]]; then
            classification="AUXILIARY"
        fi
    fi

    # =====================================================================
    # Record Classification
    # =====================================================================

    COMMIT_CLASSIFICATION["${hash}"]="${classification}:${cited_gap_id}"
    echo "  ${hash:0:7} [${classification}] ${subject}"

    if [[ "$classification" == "UNMAPPED" ]]; then
        UNCLASSIFIED_COMMITS+=("${hash}")
    fi

done

# =========================================================================
# PHASE 3: Validation Rules
# =========================================================================

info ""
info "Phase 3: Validating gap decomposition"

# Rule 1: Check for critical gaps without closures
info ""
info "Rule 3.1: Critical/HIGH gaps must have at least one closure claim"
for gap_id in "${ALL_GAP_IDS[@]}"; do
    severity="${GAP_SEVERITY[$gap_id]:-UNKNOWN}"
    if [[ "$severity" == "CRITICAL" ]] || [[ "$severity" == "HIGH" ]]; then
        # Search for gap_id in closure claims
        if git log --all --oneline 2>/dev/null | grep "$gap_id" > /dev/null; then
            pass "gap-has-closure: ${gap_id} (${severity}) is cited in commit history"
        else
            fail "gap-unmapped-critical: ${gap_id} (${severity}) has NO closure claims"
            CRITICAL_GAPS_UNMAPPED+=("${gap_id}")
        fi
    fi
done

# Rule 2: No ALIVE claims from commit count alone
info ""
info "Rule 3.2: ALIVE status must cite specific gap_id, not inferred from commit count"
if grep -q "ALIVE" "${REPO_ROOT}/${LEDGER_PATH}"; then
    # Check that every ALIVE gap has explicit closure claims
    while IFS= read -r gap_id; do
        if git log --all --oneline 2>/dev/null | grep "$gap_id" > /dev/null; then
            pass "alive-has-citation: gap with ALIVE status (${gap_id}) is explicitly cited"
        else
            fail "alive-uncited: gap with ALIVE status (${gap_id}) lacks citation in history"
        fi
    done < <(grep "ALIVE" "${REPO_ROOT}/${LEDGER_PATH}" | grep -oE "GAP_[A-Z0-9_]+" || true)
fi

# Rule 3: Every GAP_CLOSURE commit must reference a gap_id
info ""
info "Rule 3.3: Every GAP_CLOSURE commit must reference a gap_id"
for hash in "${!COMMIT_CLASSIFICATION[@]}"; do
    classification_line="${COMMIT_CLASSIFICATION[$hash]}"
    classification="${classification_line%:*}"
    cited_gap="${classification_line#*:}"

    if [[ "$classification" == "GAP_CLOSURE" ]]; then
        if [[ -z "$cited_gap" ]] || [[ "$cited_gap" == "GAP_CLOSURE" ]]; then
            fail "gap-closure-uncited: commit ${hash:0:7} claims GAP_CLOSURE but cites no gap_id"
            AUDIT_ISSUES+=("gap-closure-uncited: ${hash:0:7}")
        else
            pass "gap-closure-cited: commit ${hash:0:7} → ${cited_gap}"
        fi
    fi
done

# Rule 4: Auxiliary commits must be explicitly classified
info ""
info "Rule 3.4: Auxiliary commits must be explicitly classified in commit message"
if [[ ${#UNCLASSIFIED_COMMITS[@]} -gt 0 ]]; then
    warn "unclassified-commits: ${#UNCLASSIFIED_COMMITS[@]} commit(s) lack clear classification"
    for hash in "${UNCLASSIFIED_COMMITS[@]}"; do
        subject=$(git log -1 --format=%s "$hash" 2>/dev/null || echo "unknown")
        warn "  ${hash:0:7} $subject"
    done
fi

# =========================================================================
# PHASE 4: Summary and Exit
# =========================================================================

info ""
info "=== Gap Decomposition Audit Summary ==="
info "Total gaps: ${#ALL_GAP_IDS[@]}"
_n_unmapped="${#CRITICAL_GAPS_UNMAPPED[@]}"; info "Critical/HIGH gaps without closure: ${_n_unmapped}"
audit_issues_count=0
[[ -v AUDIT_ISSUES ]] && audit_issues_count="${#AUDIT_ISSUES[@]}"
info "GAP_CLOSURE commits without gap_id: ${audit_issues_count}"
info "Unclassified commits: ${#UNCLASSIFIED_COMMITS[@]}"
info ""
info "Validation Results:"

CRITICAL_FAILURES=0

if [[ ${#CRITICAL_GAPS_UNMAPPED[@]} -gt 0 ]]; then
    fail "critical-gaps-unmapped: ${#CRITICAL_GAPS_UNMAPPED[@]} gap(s) need closure"
    for gap in "${CRITICAL_GAPS_UNMAPPED[@]}"; do
        info "  - $gap"
    done
    CRITICAL_FAILURES=$((CRITICAL_FAILURES + 1))
else
    pass "critical-gaps-mapped: all HIGH/CRITICAL gaps have closure claims"
fi

audit_issues_count=0
[[ -v AUDIT_ISSUES ]] && audit_issues_count="${#AUDIT_ISSUES[@]}"
if [[ $audit_issues_count -gt 0 ]]; then
    fail "gap-closure-uncited: ${audit_issues_count} closure claim(s) lack gap_id"
    CRITICAL_FAILURES=$((CRITICAL_FAILURES + 1))
else
    pass "gap-closure-all-cited: all GAP_CLOSURE commits reference gap_id"
fi

if [[ ${#UNCLASSIFIED_COMMITS[@]} -gt 10 ]]; then
    fail "too-many-unclassified: ${#UNCLASSIFIED_COMMITS[@]} commits lack classification (threshold: 10)"
    CRITICAL_FAILURES=$((CRITICAL_FAILURES + 1))
elif [[ ${#UNCLASSIFIED_COMMITS[@]} -gt 0 ]]; then
    warn "unclassified-commits: ${#UNCLASSIFIED_COMMITS[@]} commit(s) are UNMAPPED"
else
    pass "all-commits-classified: every commit has a classification"
fi

info ""
if [[ $CRITICAL_FAILURES -eq 0 ]]; then
    echo "=== PASS: Gap decomposition is sound ==="
    exit 0
else
    echo "=== FAIL: Gap decomposition has ${CRITICAL_FAILURES} critical issue(s) ==="
    exit 1
fi
