#!/usr/bin/env bash
# audit_witness_markers.sh — count witness structs in src/witness.rs;
# fail if fewer than 5. Exit 1 if count < 5.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WITNESS_RS="$REPO_ROOT/src/witness.rs"
MINIMUM=5

echo "=== Witness Marker Count Audit ==="
echo ""

if [[ ! -f "$WITNESS_RS" ]]; then
    echo "FAIL: src/witness.rs not found"
    exit 1
fi

# Witnesses are generated by the witness_marker! macro. Each invocation starts
# with a name identifier as first argument, e.g.:
#   Ocel20, "ocel-2.0", WitnessFamily::Standard, ...
# Look for witness_marker! invocations by finding the macro definition first,
# then counting WitnessFamily:: references (each invocation has exactly one).

# Strategy: count witness_marker! macro blocks — each generates one witness type.
# A block starts with an uppercase ident followed by comma and a string literal.
# Also count direct pub enum/struct declarations as fallback.

# Count macro-generated witnesses: lines matching `    Name, "string",`
macro_witness_count=$(grep -cE "^[[:space:]]+[A-Z][A-Za-z0-9]+,[[:space:]]+\"" "$WITNESS_RS" || true)

# Count direct pub enum (non-macro) declarations
pub_enum_count=$(grep -cE "^pub enum [A-Z][A-Za-z0-9]+" "$WITNESS_RS" || true)

# Count direct pub struct declarations (excluding macro body)
pub_struct_count=$(grep -cE "^pub struct [A-Z][A-Za-z0-9]+" "$WITNESS_RS" || true)

# Total: macro-generated + direct
total_count=$((macro_witness_count + pub_struct_count))
# Don't double-count WitnessFamily enum itself — subtract 1 if pub enum found
# (WitnessFamily is the one top-level pub enum)

echo "Macro-generated witness markers : $macro_witness_count"
echo "Direct pub struct witnesses     : $pub_struct_count"
echo "Direct pub enum (non-witness)   : $pub_enum_count (e.g. WitnessFamily)"
echo "Total witness markers           : $total_count"
echo "Minimum required                : $MINIMUM"
echo ""

# Show first few witness names
echo "First 10 witness names:"
grep -E "^[[:space:]]+[A-Z][A-Za-z0-9]+,[[:space:]]+\"" "$WITNESS_RS" | head -10 | while IFS= read -r line; do
    echo "  $line"
done

echo ""
if [[ $total_count -lt $MINIMUM ]]; then
    echo "FAIL: Only $total_count witness markers found — minimum is $MINIMUM."
    exit 1
else
    echo "OK: $total_count witness markers found (>= $MINIMUM)."
    echo ""
    echo "RESULT: PASS"
    exit 0
fi
