"""Pydantic v2 projections of the canonical wasm4pm-compat type graph.

Manufactured by ggen from RDF type law. Every exported class retains its exact
Rust spelling in ``__rust_type__``. Empty specifications represent intentional
marker/typestate surfaces rather than invented runtime fields.
"""
from __future__ import annotations

from typing import Any, ClassVar, ForwardRef, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, create_model

JsonNumber = int | float


class CompatModel(BaseModel):
    """Strict base for synchronized compatibility projections."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)


# (rust_type, ((python_name, field_type, optional, array, alias), ...))
_SPECS: dict[str, tuple[str, tuple[tuple[str, str, bool, bool, str | None], ...]]] = {
    "Admission": ("Admission<T, W>", ()),
    "Admitted": ("Admitted", ()),
    "AdmittedToExportable": ("AdmittedToExportable", ()),
    "AdmittedToProjected": ("AdmittedToProjected", ()),
    "AdmittedToReceipted": ("AdmittedToReceipted", ()),
    "AffidavitReceiptChain": ("AffidavitReceiptChain", ()),
    "AggregationView": ("AggregationView", ()),
    "AlignmentPaper": ("AlignmentPaper", ()),
    "AlphaMiner": ("AlphaMiner", ()),
    "AnalyticalView": ("AnalyticalView", ()),
    "Arc": ("Arc", (("from_", "string", False, False, "from"), ("to", "string", False, False, None), ("weight", "number", True, False, None), )),
    "ArcDirection": ("ArcDirection", ()),
    "AssertionRef": ("AssertionRef", ()),
    "Attribute": ("Attribute", (("key", "string", False, False, None), ("own_attributes", "Attribute", True, True, None), ("value", "AttributeValue", False, False, None), )),
    "AttributeValue": ("AttributeValue", ()),
    "AuthorizationEnvelope": ("AuthorizationEnvelope", (("allowed_nodes", "PowlNodeId", False, True, None), ("authorization_id", "string", False, False, None), ("challenge_nonce", "string", False, False, None), ("domain_digest", "string", False, False, None), ("expires_unix_ms", "number", False, False, None), ("issued_unix_ms", "number", False, False, None), ("model_digest", "string", False, False, None), ("proof_digest", "string", False, False, None), ("single_use", "boolean", False, False, None), ("subject", "string", False, False, None), )),
    "Between01Constraint": ("Between01<NUM, DEN>", ()),
    "Blake3Hash": ("Blake3Hash", ()),
    "BpmnEdge": ("BpmnEdge", (("id", "string", False, False, None), ("source", "string", False, False, None), ("target", "string", False, False, None), )),
    "BpmnLane": ("BpmnLane", (("id", "string", False, False, None), ("name", "string", False, False, None), ("nodes", "string", False, True, None), )),
    "BpmnModel": ("BpmnModel", ()),
    "BpmnNode": ("BpmnNode", (("id", "string", False, False, None), ("kind", "string", False, False, None), ("name", "string", True, False, None), )),
    "BpmnProcess": ("BpmnProcess", (("edges", "BpmnEdge", False, True, None), ("lanes", "BpmnLane", False, True, None), ("nodes", "BpmnNode", False, True, None), )),
    "Capability": ("Capability", ()),
    "CapabilityObservation": ("CapabilityObservation", (("capability", "Capability", False, False, None), ("code", "string", False, False, None), ("owner", "CapabilityOwner", False, False, None), ("reason", "string", False, False, None), ("required_feature", "string", True, False, None), ("state", "CapabilityState", False, False, None), )),
    "CapabilityOwner": ("CapabilityOwner", ()),
    "CapabilityState": ("CapabilityState", ()),
    "CausalBinding": ("CausalBinding", (("source_tasks", "string", False, True, None), ("target_tasks", "string", False, True, None), )),
    "CausalConsistencyWitness": ("CausalConsistencyWitness", ()),
    "CausalNet": ("CausalNet", ()),
    "CausalNetRefusal": ("CausalNetRefusal", ()),
    "CausalityGraph": ("CausalityGraph", ()),
    "CertificateClaim": ("CertificateClaim", ()),
    "CertifiedPowl": ("CertifiedPowl", (("bounds", "VerificationBounds", False, False, None), ("claim", "CertificateClaim", False, False, None), ("domain_digest", "string", False, False, None), ("model", "Powl", False, False, None), ("model_digest", "string", False, False, None), ("proof", "ProofTerm", False, False, None), ("proof_digest", "string", False, False, None), ("schema", "string", False, False, None), ("subject", "string", False, False, None), ("version", "string", False, False, None), )),
    "ChoiceGraph": ("ChoiceGraph", ()),
    "ChoiceGraphEdge": ("ChoiceGraphEdge", ()),
    "ChoiceGraphError": ("ChoiceGraphError", ()),
    "ChoiceGraphNode": ("ChoiceGraphNode", ()),
    "CommutationWitness": ("CommutationWitness", (("left", "PowlNodeId", False, False, None), ("right", "PowlNodeId", False, False, None), )),
    "CompareOp": ("CompareOp", ()),
    "CompatDiagnostic": ("CompatDiagnostic", (("message", "string", False, False, None), ("severity", "string", False, False, None), ("variant", "string", False, False, None), )),
    "ComplexModel": ("ComplexModel", (("nodes", "string", False, True, None), )),
    "ConditionCellConstraint": ("ConditionCell<BITS>", ()),
    "ConformanceAuthority": ("ConformanceAuthority", ()),
    "ConformanceResult": ("ConformanceResult", (("deviating_traces", "number", False, False, None), ("fitness", "number", False, False, None), ("fitting_traces", "number", False, False, None), ("precision", "number", True, False, None), ("total_traces", "number", False, False, None), )),
    "ConformanceVerdict": ("ConformanceVerdict", (("is_perfect", "boolean", False, False, None), )),
    "ConformanceWitness": ("ConformanceWitness", ()),
    "ControlFlowPerspectiveWitness": ("ControlFlowPerspectiveWitness", ()),
    "ConvergenceWitness": ("ConvergenceWitness", ()),
    "CorrelationSchema": ("CorrelationSchema", ()),
    "CrossLogCorrelationWitness": ("CrossLogCorrelationWitness", ()),
    "CycleWitness": ("CycleWitness", ()),
    "DFG": ("DFG", (("edges", "DFGEdge", False, True, None), ("nodes", "DFGNode", False, True, None), )),
    "DFGEdge": ("DFGEdge", (("frequency", "number", False, False, None), ("source", "string", False, False, None), ("target", "string", False, False, None), )),
    "DFGNode": ("DFGNode", (("activity", "string", False, False, None), ("frequency", "number", False, False, None), )),
    "DataPerspectiveWitness": ("DataPerspectiveWitness", ()),
    "DeclareConstraint": ("DeclareConstraint", (("activities", "string", False, True, None), ("constraint_type", "string", False, False, None), )),
    "DeclareConstraints": ("DeclareConstraints", ()),
    "DeclareFamily": ("DeclareFamily", ()),
    "DeclareModel": ("DeclareModel", (("constraints", "DeclareConstraint", False, True, None), )),
    "DenseError": ("DenseError", ()),
    "DenseIndex": ("DenseIndex", ()),
    "DerivedPredicate": ("DerivedPredicate", (("body", "PddlCondition", False, False, None), ("head", "Pddl8Atom", False, False, None), )),
    "DfCmAxis": ("DfCmAxis", (("description", "string", True, False, None), ("name", "string", False, False, None), ("variants", "string", False, True, None), )),
    "DfCmCell": ("DfCmCell", (("actual_standing", "Standing", False, False, None), ("coords", "string", False, True, None), ("expected_standing", "Standing", False, False, None), ("fixture", "string", True, False, None), ("is_impossible", "boolean", False, False, None), ("manufacture_witness", "string", True, False, None), ("refusal_reason", "string", True, False, None), )),
    "DfCmFailure": ("DfCmFailure", (("actual", "Standing", False, False, None), ("coords", "string", False, True, None), ("expected", "Standing", False, False, None), ("reason", "string", True, False, None), )),
    "DfCmMatrix": ("DfCmMatrix", (("axes", "DfCmAxis", False, True, None), ("cells", "DfCmCell", False, True, None), ("name", "string", False, False, None), )),
    "DfCmReport": ("DfCmReport", (("coverage", "number", False, False, None), ("evaluated", "number", False, False, None), ("failures", "DfCmFailure", False, True, None), ("matrix_name", "string", False, False, None), ("pass_rate", "number", False, False, None), ("passing", "number", False, False, None), ("total", "number", False, False, None), )),
    "DiagnosticCatalogEntry": ("DiagnosticCatalogEntry", (("code", "string", False, False, None), ("message", "string", False, False, None), ("name", "string", False, False, None), ("repair", "string", False, False, None), ("severity", "string", False, False, None), )),
    "DiagnosticPayload": ("DiagnosticPayload", (("code", "string", False, False, None), ("message", "string", False, False, None), )),
    "DirectlyFollowsGraph": ("DirectlyFollowsGraph", ()),
    "DivergenceWitness": ("DivergenceWitness", ()),
    "DoctorCheck": ("DoctorCheck", (("capability", "Capability", True, False, None), ("code", "string", False, False, None), ("detail", "string", False, False, None), ("repair", "RepairAction", True, False, None), ("state", "DoctorCheckState", False, False, None), ("summary", "string", False, False, None), )),
    "DoctorCheckState": ("DoctorCheckState", ()),
    "DoctorProfile": ("DoctorProfile", ()),
    "DoctorReport": ("DoctorReport", (("capabilities", "CapabilityObservation", False, True, None), ("checks", "DoctorCheck", False, True, None), ("crate_name", "string", False, False, None), ("crate_version", "string", False, False, None), ("profile", "DoctorProfile", False, False, None), ("repairs", "RepairAction", False, True, None), ("schema", "string", False, False, None), ("schema_version", "number", False, False, None), ("standing", "DoctorStanding", False, False, None), )),
    "DoctorStanding": ("DoctorStanding", ()),
    "DurationConstraint": ("DurationConstraint", ()),
    "DurativeAction": ("DurativeAction", ()),
    "EdgeContract": ("EdgeContract", (("from_", "PowlNodeId", False, False, "from"), ("to", "PowlNodeId", False, False, None), )),
    "Error": ("Error", ()),
    "Event": ("Event", (("activity", "string", False, False, None), ("lifecycle", "string", True, False, None), ("resource", "string", True, False, None), ("timestamp_ns", "number", True, False, None), )),
    "EventLog": ("EventLog", (("attributes", "Record<string, string>", False, False, None), ("traces", "Trace", False, True, None), )),
    "EventLogClassifier": ("EventLogClassifier", (("keys", "string", False, True, None), ("name", "string", False, False, None), )),
    "EventLogExtension": ("EventLogExtension", (("name", "string", False, False, None), ("prefix", "string", False, False, None), ("uri", "string", False, False, None), )),
    "EventLogKnowledgeGraph": ("EventLogKnowledgeGraph", (("triples", "Triple", False, True, None), )),
    "EventStream": ("EventStream", ()),
    "Evidence": ("Evidence", (("inner", "any", False, False, None), ("state", "string", False, False, None), ("witness", "string", False, False, None), )),
    "ExecutionReceiptShape": ("ExecutionReceiptShape", ()),
    "ExecutionSelection": ("ExecutionSelection", ()),
    "Exportable": ("Exportable", ()),
    "ExportableToReceipted": ("ExportableToReceipted", ()),
    "FailedTransition": ("FailedTransition", (("missing_places", "string", False, True, None), ("transition_id", "string", False, False, None), )),
    "FlatCase": ("FlatCase", (("case_id", "string", False, False, None), ("event_ids", "string", False, True, None), ("trace", "string", False, True, None), )),
    "FlatIncidenceMatrix": ("FlatIncidenceMatrix", (("data", "number", False, True, None), ("places_count", "number", False, False, None), ("transitions_count", "number", False, False, None), )),
    "FlatLog": ("FlatLog", (("cases", "FlatCase", False, True, None), ("object_type", "string", False, False, None), )),
    "GradNeedsBenchmarkGating": ("GraduationReason::NeedsBenchmarkGating", ()),
    "GradNeedsConformanceExecution": ("GraduationReason::NeedsConformanceExecution", ()),
    "GradNeedsDiscovery": ("GraduationReason::NeedsDiscovery", ()),
    "GradNeedsObjectCentricQuery": ("GraduationReason::NeedsObjectCentricQuery", ()),
    "GradNeedsReplay": ("GraduationReason::NeedsReplay", ()),
    "GradRebuildingProcessMiningLocally": ("GraduationReason::RebuildingProcessMiningLocally", ()),
    "GraduationCandidate": ("GraduationCandidate", ()),
    "GraphNodeProof": ("GraphNodeProof", (("after", "AssertionRef", False, False, None), ("before", "AssertionRef", False, False, None), ("node", "PowlNodeId", False, False, None), ("proof", "ProofTerm", False, False, None), )),
    "Identifiers": ("CaseId, ActivityId, ObjectId, EventId", ()),
    "InductiveMiner": ("InductiveMiner", ()),
    "IngestionKnowledgeBase": ("IngestionKnowledgeBase", ()),
    "Intent": ("Intent", ()),
    "InteropBridge": ("InteropBridge", ()),
    "LeafNode": ("LeafNode", (("id", "string", False, False, None), ("label", "string", False, False, None), )),
    "LifecycleAuthority": ("LifecycleAuthority", ()),
    "LifecycleWitness": ("LifecycleWitness", ()),
    "LogSkeleton": ("LogSkeleton", ()),
    "LossChain": ("LossChain", (("steps", "NamedLoss", False, True, None), )),
    "LossReport": ("LossReport", (("lost", "any", False, False, None), ("policy", "string", False, False, None), ("projection", "string", False, False, None), )),
    "Metric": ("Metric", (("dir", "MetricDir", False, False, None), ("expr", "MetricExpr", False, False, None), )),
    "MetricDir": ("MetricDir", ()),
    "MetricExpr": ("MetricExpr", ()),
    "MiningAuthority": ("MiningAuthority", ()),
    "MiningWitness": ("MiningWitness", ()),
    "Mode": ("Mode", ()),
    "MultiPerspectiveLog": ("MultiPerspectiveLog", ()),
    "NamedLoss": ("NamedLoss", (("category", "string", False, False, None), ("projection", "string", False, False, None), )),
    "NodeKind": ("NodeKind", ()),
    "NumericEffect": ("NumericEffect", ()),
    "NumericExpr": ("NumericExpr", ()),
    "NumericOp": ("NumericOp", ()),
    "OCEL": ("OCEL", (("event_types", "OCELType", False, True, None), ("events", "OCELEvent", False, True, None), ("object_types", "OCELType", False, True, None), ("objects", "OCELObject", False, True, None), )),
    "OCELAttributeValue": ("OCELAttributeValue", ()),
    "OCELEvent": ("OCELEvent", ()),
    "OCELEventAttribute": ("OCELEventAttribute", (("name", "string", False, False, None), ("value", "OCELAttributeValue", False, False, None), )),
    "OCELObject": ("OCELObject", (("attributes", "OCELObjectAttribute", False, True, None), ("id", "string", False, False, None), ("object_type", "string", False, False, None), ("relationships", "OCELRelationship", False, True, None), )),
    "OCELObjectAttribute": ("OCELObjectAttribute", ()),
    "OCELRecord": ("OCELRecord", ()),
    "OCELRelationship": ("OCELRelationship", (("object_id", "string", False, False, None), ("qualifier", "string", False, False, None), )),
    "OCELType": ("OCELType", (("attributes", "OCELTypeAttribute", False, True, None), ("name", "string", False, False, None), )),
    "OCELTypeAttribute": ("OCELTypeAttribute", (("name", "string", False, False, None), ("value_type", "string", False, False, None), )),
    "ObjectCentricPetriNet": ("ObjectCentricPetriNet", ()),
    "ObjectCentricPetriNetPaper": ("ObjectCentricPetriNetPaper", ()),
    "ObjectLifecycle": ("ObjectLifecycle", ()),
    "ObjectTypeCardinality": ("ObjectTypeCardinality", (("max_occurrence", "number", True, False, None), ("min_occurrence", "number", False, False, None), ("object_type", "string", False, False, None), )),
    "ObservedStep": ("ObservedStep", (("action", "string", False, False, None), ("after_digest", "string", False, False, None), ("before_digest", "string", False, False, None), ("node", "PowlNodeId", False, False, None), ("ordinal", "number", False, False, None), )),
    "OcPetriNets": ("OcPetriNets", ()),
    "Ocel20": ("Ocel20", ()),
    "OcelAttributeType": ("OcelAttributeType", ()),
    "OcelAttributeValue": ("OcelAttributeValue", (("value", "any", False, False, None), )),
    "OcelEvent": ("OcelEvent", (("attributes", "OcelEventAttribute", False, True, None), ("id", "string", False, False, None), ("relationships", "OcelRelationship", False, True, None), ("time", "any", False, False, None), ("type", "string", False, False, None), )),
    "OcelEventAttribute": ("OcelEventAttribute", (("name", "string", False, False, None), ("value", "any", False, False, None), )),
    "OcelEventType": ("OcelEventType", ()),
    "OcelLog": ("OcelLog", (("eventTypes", "OcelType", False, True, None), ("events", "OcelEvent", False, True, None), ("objectTypes", "OcelType", False, True, None), ("objects", "OcelObject", False, True, None), )),
    "OcelObject": ("OcelObject", (("attributes", "OcelObjectAttribute", False, True, None), ("id", "string", False, False, None), ("type", "string", False, False, None), )),
    "OcelObjectAttribute": ("OcelObjectAttribute", (("name", "string", False, False, None), ("time", "any", False, False, None), ("value", "any", False, False, None), )),
    "OcelObjectType": ("OcelObjectType", ()),
    "OcelRelationship": ("OcelRelationship", (("objectId", "string", False, False, None), ("qualifier", "string", False, False, None), )),
    "OcelTuple": ("OcelTuple", ()),
    "OcelType": ("OcelType", (("attributes", "OcelTypeAttribute", False, True, None), ("name", "string", False, False, None), )),
    "OcelTypeAttribute": ("OcelTypeAttribute", (("name", "string", False, False, None), ("type", "string", False, False, None), )),
    "OcpqPaper": ("OcpqPaper", ()),
    "OcpqQuery": ("OcpqQuery", ()),
    "OperationalView": ("OperationalView", ()),
    "OrderEdge": ("OrderEdge", (("from_", "number", False, False, "from"), ("to", "number", False, False, None), )),
    "PackedKeyTable": ("PackedKeyTable", ()),
    "Parsed": ("Parsed", ()),
    "ParsedToAdmitted": ("ParsedToAdmitted", ()),
    "ParsedToRefused": ("ParsedToRefused", ()),
    "PcpRefusal": ("PcpRefusal", ()),
    "Pddl31Action": ("Pddl31Action", ()),
    "Pddl31Domain": ("Pddl31Domain", ()),
    "Pddl31Problem": ("Pddl31Problem", ()),
    "Pddl8ActionSchema": ("Pddl8ActionSchema", ()),
    "Pddl8Atom": ("Pddl8Atom", (("args", "string", False, True, None), ("pred", "string", False, False, None), )),
    "Pddl8Domain": ("Pddl8Domain", ()),
    "Pddl8ExecutionLog": ("Pddl8ExecutionLog", (("chain_hash", "string", False, False, None), ("goal_reached", "boolean", False, False, None), ("steps", "Pddl8StepResult", False, True, None), )),
    "Pddl8ExecutionReceipt": ("Pddl8ExecutionReceipt", (("chain_hash", "string", False, False, None), ("goal_reached", "boolean", False, False, None), ("goal_root", "string", False, False, None), ("plan_root", "string", False, False, None), ("state_root", "string", False, False, None), ("step_count", "number", False, False, None), )),
    "Pddl8GroundAction": ("Pddl8GroundAction", (("add_effects", "Pddl8GroundAtom", False, True, None), ("del_effects", "Pddl8GroundAtom", False, True, None), ("label", "string", False, False, None), ("preconditions", "Pddl8GroundAtom", False, True, None), ("schema_name", "string", False, False, None), )),
    "Pddl8GroundAtom": ("Pddl8GroundAtom", (("args", "string", False, True, None), ("pred", "string", False, False, None), )),
    "Pddl8Problem": ("Pddl8Problem", ()),
    "Pddl8StepResult": ("Pddl8StepResult", (("admitted", "boolean", False, False, None), ("epoch_after", "number", False, False, None), ("label", "string", False, False, None), ("op_index", "number", False, False, None), ("receipt_hash", "string", False, False, None), )),
    "Pddl8Tape": ("Pddl8Tape", (("ops", "Pddl8TapeOp", False, True, None), )),
    "Pddl8TapeOp": ("Pddl8TapeOp", (("action", "Pddl8GroundAction", False, False, None), ("index", "number", False, False, None), ("label", "string", False, False, None), ("pred_mask", "number", False, False, None), )),
    "PddlCondition": ("PddlCondition", ()),
    "PddlConstraint": ("PddlConstraint", (("constraint", "TrajectoryConstraint", False, False, None), ("name", "string", True, False, None), )),
    "PddlEffect": ("PddlEffect", ()),
    "PddlEvent": ("PddlEvent", ()),
    "PddlFunction": ("PddlFunction", (("name", "string", False, False, None), ("params", "string", False, True, None), )),
    "PddlPreference": ("PddlPreference", (("constraint", "TrajectoryConstraint", False, False, None), ("name", "string", True, False, None), )),
    "PddlProcess": ("PddlProcess", ()),
    "PddlType": ("PddlType", (("name", "string", False, False, None), ("parent", "string", True, False, None), )),
    "PerspectivePath": ("PerspectivePath", (("steps", "PerspectiveStep", False, True, None), )),
    "PerspectiveStep": ("PerspectiveStep", (("relationship", "string", False, False, None), ("target_type", "string", False, False, None), )),
    "PetriNet": ("PetriNet", (("arcs", "Arc", False, True, None), ("places", "Place", False, True, None), ("transitions", "Transition", False, True, None), )),
    "Place": ("Place", (("id", "string", False, False, None), ("name", "string", True, False, None), )),
    "Pm4pyApiGrammar": ("Pm4pyApiGrammar", ()),
    "PmaxConsumerGrammar": ("PmaxConsumerGrammar", ()),
    "Powl": ("Powl", (("edges", "OrderEdge", False, True, None), ("nodes", "PowlNode", False, True, None), ("root", "number", True, False, None), )),
    "Powl8Op": ("Powl8Op", ()),
    "PowlChoiceNode": ("PowlChoiceNode", (("branches", "PowlNodeId", False, True, None), )),
    "PowlComposition": ("PowlComposition", ()),
    "PowlNode": ("PowlNode", (("id", "number", False, False, None), ("kind", "string", False, False, None), )),
    "PowlNodeId": ("PowlNodeId", ()),
    "PowlNodeKind": ("PowlNodeKind", ()),
    "PowlPaper": ("PowlPaper", ()),
    "PowlRefusal": ("PowlRefusal", ()),
    "Precondition": ("Precondition", ()),
    "PredictionTarget": ("PredictionTarget", ()),
    "PredictiveMonitoringFamily": ("PredictiveMonitoringFamily", ()),
    "ProcessCube": ("ProcessCube", ()),
    "ProcessCubePaper": ("ProcessCubePaper", ()),
    "ProcessTree": ("ProcessTree", (("nodes", "ProcessTreeNode", False, True, None), ("root", "number", True, False, None), )),
    "ProcessTreeNode": ("ProcessTreeNode", (("children", "number", True, True, None), ("kind", "string", False, False, None), ("label", "string", True, False, None), )),
    "Projected": ("Projected", ()),
    "ProjectedToExportable": ("ProjectedToExportable", ()),
    "ProjectedToReceipted": ("ProjectedToReceipted", ()),
    "ProofTerm": ("ProofTerm", ()),
    "Raw": ("Raw", ()),
    "RawToParsed": ("RawToParsed", ()),
    "Receipt": ("Receipt", (("final_hash_chain", "string", False, False, None), ("model_id", "string", False, False, None), ("verdict", "ConformanceVerdict", False, False, None), )),
    "ReceiptFamily": ("ReceiptFamily", ()),
    "Receipted": ("Receipted", ()),
    "Refusal": ("Refusal<R, W>", ()),
    "Refused": ("Refused", ()),
    "RefusedProjection": ("RefusedProjection", ()),
    "RepairAction": ("RepairAction", (("code", "string", False, False, None), ("command", "string", True, False, None), ("owner", "CapabilityOwner", False, False, None), ("reversible", "boolean", False, False, None), ("summary", "string", False, False, None), )),
    "ReplayAuthority": ("ReplayAuthority", ()),
    "ReplayWitness": ("ReplayWitness", ()),
    "RequireIsTrueConstraint": ("Require<{ EXPR }>", ()),
    "ResidualFailset": ("ResidualFailset", (("deadlocked_places", "string", False, True, None), ("residual_marking", "Record<string, string>", False, False, None), ("unreplayable_transitions", "FailedTransition", False, True, None), )),
    "ResourcePerspectiveWitness": ("ResourcePerspectiveWitness", ()),
    "RouteDecision": ("RouteDecision", (("intent", "Intent", False, False, None), ("reason", "string", False, False, None), ("repair", "RepairAction", True, False, None), ("required_feature", "string", True, False, None), ("state", "RouteState", False, False, None), ("target", "RouteTarget", False, False, None), )),
    "RoutePlan": ("RoutePlan", (("decisions", "RouteDecision", False, True, None), ("repairs", "RepairAction", False, True, None), ("schema", "string", False, False, None), ("standing", "DoctorStanding", False, False, None), )),
    "RouteState": ("RouteState", ()),
    "RouteTarget": ("RouteTarget", ()),
    "RustTypestateLaw": ("RustTypestateLaw", ()),
    "SeparableWfNet": ("SeparableWfNet<SOUNDNESS>", ()),
    "SeparableWfNetPaper": ("SeparableWfNetPaper", ()),
    "SoundnessClaimed": ("SoundnessClaimed", ()),
    "SoundnessUnknown": ("SoundnessUnknown", ()),
    "SoundnessWitnessed": ("SoundnessWitnessed", ()),
    "StandaloneChoiceGraphNode": ("StandaloneChoiceGraphNode", ()),
    "Standing": ("Standing", ()),
    "StreamingEvidenceWitness": ("StreamingEvidenceWitness", ()),
    "StrictBoundary": ("ExportBoundaryConst<HAS_WITNESS, HAS_ROUND_TRIP>", ()),
    "TemporalConstraint": ("TemporalConstraint", ()),
    "TemporalExecutionReceipt": ("TemporalExecutionReceipt", (("chain_hash", "string", False, False, None), ("goal_reached", "boolean", False, False, None), ("goal_root", "string", False, False, None), ("makespan", "number", False, False, None), ("plan_root", "string", False, False, None), ("requirements", "string", False, True, None), ("state_root", "string", False, False, None), ("step_count", "number", False, False, None), )),
    "TemporalPlan": ("TemporalPlan", (("makespan", "number", False, False, None), ("metric_value", "number", True, False, None), ("steps", "TemporalPlanStep", False, True, None), )),
    "TemporalPlanStep": ("TemporalPlanStep", (("action_name", "string", False, False, None), ("args", "string", False, True, None), ("duration", "number", False, False, None), ("start_time", "number", False, False, None), )),
    "TemporalProfileWitness": ("TemporalProfileWitness", ()),
    "TimeAwareWitness": ("TimeAwareWitness", ()),
    "TimePerspectiveWitness": ("TimePerspectiveWitness", ()),
    "TimeSpecifier": ("TimeSpecifier", ()),
    "TimedLiteral": ("TimedLiteral", (("atom", "Pddl8Atom", False, False, None), ("negated", "boolean", False, False, None), ("time", "number", False, False, None), )),
    "TokenReplayResult": ("TokenReplayResult", (("consumed_tokens", "number", False, False, None), ("fitness", "number", False, False, None), ("missing_tokens", "number", False, False, None), ("produced_tokens", "number", False, False, None), ("remaining_tokens", "number", False, False, None), )),
    "Trace": ("Trace", (("events", "Event", False, True, None), ("id", "string", False, False, None), )),
    "TraceConstraint": ("TraceConstraint", ()),
    "TrajectoryConstraint": ("TrajectoryConstraint", ()),
    "Transition": ("Transition", (("id", "string", False, False, None), ("label", "string", True, False, None), )),
    "Triple": ("Triple", (("object", "string", False, False, None), ("predicate", "string", False, False, None), ("subject", "string", False, False, None), )),
    "TypedLoopNodeArityConstraint": ("TypedLoopNode<ARITY>", ()),
    "TypedPowlLoopNode": ("TypedPowlLoopNode", ()),
    "ValidationError": ("ValidationError", (("code", "string", False, False, None), ("message", "string", False, False, None), )),
    "ValidationReport": ("ValidationReport", (("errors", "ValidationError", False, True, None), ("valid", "boolean", False, False, None), )),
    "VariantRef": ("VariantRef", ()),
    "VerificationBounds": ("VerificationBounds", (("max_choice_visits", "number", False, False, None), ("max_proof_depth", "number", False, False, None), ("max_selection_depth", "number", False, False, None), ("max_states", "number", False, False, None), ("max_trace_steps", "number", False, False, None), )),
    "VerificationReport": ("VerificationReport", (("failset", "ResidualFailset", True, False, None), ("is_compliant", "boolean", False, False, None), )),
    "Wasm4pmBridge": ("Wasm4pmBridge", ()),
    "WfNet2Powl": ("WfNet2Powl", ()),
    "WfNetConst": ("WfNetConst<SOUNDNESS>", ()),
    "WfNetSoundnessPaper": ("WfNetSoundnessPaper", ()),
    "WorkflowNet": ("WorkflowNet", ()),
    "WorkflowPattern": ("WorkflowPattern", ()),
    "WorkflowPatternsPaper": ("WorkflowPatternsPaper", ()),
    "XESImportOptions": ("XESImportOptions", ()),
    "XESOuterLogData": ("XESOuterLogData", ()),
    "XESParseError": ("XESParseError", ()),
    "Xes1849": ("Xes1849", ()),
    "XesConceptExt": ("XesConceptExt", ()),
    "XesEvent": ("XesEvent", (("attributes", "Record<string, string>", False, False, None), )),
    "XesExtension": ("XesExtension", (("name", "string", False, False, None), ("prefix", "string", False, False, None), ("uri", "string", False, False, None), )),
    "XesLifecycleExt": ("XesLifecycleExt", ()),
    "XesLog": ("XesLog", (("extensions", "XesExtension", False, True, None), ("name", "string", False, False, None), ("traces", "XesTrace", False, True, None), )),
    "XesTrace": ("XesTrace", (("events", "XesEvent", False, True, None), ("name", "string", False, False, None), )),
    "YawlPaper": ("YawlPaper", ()),
    "oc_powl": ("oc_powl", (("model", "ComplexModel", False, False, None), )),
}

_PRIMITIVES: dict[str, Any] = {
    "string": str,
    "number": JsonNumber,
    "boolean": bool,
    "any": Any,
    "Record<string, string>": dict[str, str],
    "Record<string, any>": dict[str, Any],
}


def _annotation(field_type: str, is_array: bool, is_optional: bool) -> Any:
    annotation = _PRIMITIVES[field_type] if field_type in _PRIMITIVES else ForwardRef(field_type)
    if is_array:
        annotation = list[annotation]
    if is_optional:
        annotation = Optional[annotation]
    return annotation


for _name, (_rust_type, _fields) in _SPECS.items():
    _definitions: dict[str, tuple[Any, Any]] = {}
    for _python_name, _field_type, _optional, _array, _alias in _fields:
        _field = None if _optional else ...
        if _alias is not None:
            _field = Field(_field, alias=_alias)
        _definitions[_python_name] = (_annotation(_field_type, _array, _optional), _field)
    _model = create_model(_name, __base__=CompatModel, **_definitions)
    _model.__module__ = __name__
    _model.__rust_type__ = _rust_type
    globals()[_name] = _model

for _name in _SPECS:
    globals()[_name].model_rebuild(_types_namespace=globals())

__all__ = ["CompatModel", "JsonNumber", *_SPECS]
