#!/usr/bin/env bash
# audit-no-tools-in-compat.sh.ggen: Enforcement audit for wasm4pm-compat
# Constitutional Equation: NO EXECUTION ENGINES IN COMPAT LAYER
#
# Purpose: Verify that NO engine functions (mining, conformance, replay, alignment,
# receipting, benchmarking) are exported from the compat layer. These are the
# ONLY canonical paths to engine capabilities:
#   - graduation bridge (GraduateToWasm4pm trait)
#   - wasm4pm external dependency (once stabilized)
#   - explicit engine crate import (wasm4pm-engine or similar)
#
# Forbidden Exports (REFUSE if found):
#   - simulate_replay — execution engine (belongs in wasm4pm-engine)
#   - compute_alignment — execution engine (belongs in wasm4pm-engine)
#   - discover_model — process mining (belongs in wasm4pm-engine)
#   - execute_ocpq — object-centric query (belongs in wasm4pm-engine)
#   - run_conformance — conformance checking (belongs in wasm4pm-engine)
#   - mint_receipt — proof generation (belongs in wasm4pm-engine)
#   - benchmark_gate_run — performance measurement (belongs in wasm4pm-engine)
#
# Additional Forbidden Patterns:
#   - pub fn <forbidden_name> in src/*.rs (direct export)
#   - pub async fn <forbidden_name> in src/*.rs (async export)
#   - pub struct <forbidden_name> in src/*.rs (type export smuggling)
#   - #[export_name = "<forbidden_name>"] in src/*.rs (WASM export bypass)
#   - impl.*<forbidden_name> in src/*.rs (trait impl smuggling)
#   - "engine::" use statements in src/*.rs without graduation bridge
#   - direct function pointers to engine functions
#
# Input variables (from ggen context):
#   REPO_ROOT — git repo root
#   COMPAT_SRC — path to src directory (default: src)
#   COMPAT_GENERATED — path to generated artifacts (default: target/generated)
#   ENGINE_NAMES — comma-separated list of engine function names
#   GRADUATION_BRIDGE_REQUIRED — bool, true if wasm4pm feature requires graduation trait
#
# Exit Codes:
#   0 — PASS: All checks clear, no forbidden exports detected
#   1 — FAIL: At least one forbidden export or pattern found
#   2 — ERROR: Script configuration or repo state invalid
#
# Auto-generated by ggen from wasm4pm-compat.ttl --- DO NOT EDIT MANUALLY
# Source: wasm4pm-compat.ttl (AuditPolicy: NoToolsInCompat)
# Regenerate with: ggen sync --template audit-no-tools-in-compat.sh.ggen

set -euo pipefail

# =============================================================================
# Configuration and Defaults
# =============================================================================

REPO_ROOT="${REPO_ROOT:=$(git rev-parse --show-toplevel 2>/dev/null || echo '.')}"
COMPAT_SRC="${COMPAT_SRC:=${REPO_ROOT}/src}"
COMPAT_GENERATED="${COMPAT_GENERATED:=${REPO_ROOT}/target/generated}"
GRADUATION_BRIDGE_REQUIRED="${GRADUATION_BRIDGE_REQUIRED:=true}"

# Canonical list of engine function names that MUST NOT be exported from compat
ENGINE_NAMES="${ENGINE_NAMES:=simulate_replay,compute_alignment,discover_model,execute_ocpq,run_conformance,mint_receipt,benchmark_gate_run}"
IFS=',' read -ra FORBIDDEN_EXPORTS <<< "$ENGINE_NAMES"

# Counter tracking
PASS_COUNT=0
FAIL_COUNT=0
WARN_COUNT=0

# Color output (for terminals)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# =============================================================================
# Helper Functions
# =============================================================================

pass() {
    echo -e "${GREEN}PASS${NC}  $1"
    (( PASS_COUNT += 1 )) || true
}

fail() {
    echo -e "${RED}FAIL${NC}  $1"
    (( FAIL_COUNT += 1 )) || true
}

warn() {
    echo -e "${YELLOW}WARN${NC}  $1"
    (( WARN_COUNT += 1 )) || true
}

info() {
    echo "INFO  $1"
}

check_file_exists() {
    local file="$1"
    local label="$2"
    if [[ ! -f "$file" ]]; then
        fail "$label: file not found: $file"
        return 1
    fi
    return 0
}

# =============================================================================
# Section 1: Environment Validation
# =============================================================================

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║  AUDIT: NO TOOLS IN COMPAT                                                ║"
echo "║  Enforce: Engine functions MUST NOT be exported from wasm4pm-compat       ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

if [[ ! -d "$REPO_ROOT/.git" ]]; then
    fail "repo-valid: not a git repository: $REPO_ROOT"
    exit 2
fi
pass "repo-valid: git repository detected at $REPO_ROOT"

if [[ ! -d "$COMPAT_SRC" ]]; then
    fail "compat-src-exists: source directory missing: $COMPAT_SRC"
    exit 2
fi
pass "compat-src-exists: source directory found at $COMPAT_SRC"

echo ""
echo "─ Configuration ─────────────────────────────────────────────────────────────"
echo "  REPO_ROOT:                    $REPO_ROOT"
echo "  COMPAT_SRC:                   $COMPAT_SRC"
echo "  COMPAT_GENERATED:             $COMPAT_GENERATED"
echo "  GRADUATION_BRIDGE_REQUIRED:   $GRADUATION_BRIDGE_REQUIRED"
echo "  Forbidden Exports:            ${FORBIDDEN_EXPORTS[*]}"
echo ""

# =============================================================================
# Section 2: Direct Function Export Detection
# =============================================================================

echo "─ SCAN 1: Direct Function Exports ──────────────────────────────────────────"

for engine_fn in "${FORBIDDEN_EXPORTS[@]}"; do
    info "scanning for: pub fn $engine_fn"

    # Pattern 1: pub fn <name>( ... )
    if grep -r "pub\s\+fn\s\+$engine_fn\s*(" "$COMPAT_SRC" 2>/dev/null | grep -v "// ALLOWED" > /dev/null; then
        fail "direct-export-$engine_fn: found 'pub fn $engine_fn' in source"
        grep -r "pub\s\+fn\s\+$engine_fn\s*(" "$COMPAT_SRC" 2>/dev/null | sed 's/^/    > /'
    else
        pass "direct-export-$engine_fn: no direct 'pub fn $engine_fn' export"
    fi

    # Pattern 2: pub async fn <name>( ... )
    if grep -r "pub\s\+async\s\+fn\s\+$engine_fn\s*(" "$COMPAT_SRC" 2>/dev/null | grep -v "// ALLOWED" > /dev/null; then
        fail "async-export-$engine_fn: found 'pub async fn $engine_fn' in source"
        grep -r "pub\s\+async\s\+fn\s\+$engine_fn\s*(" "$COMPAT_SRC" 2>/dev/null | sed 's/^/    > /'
    else
        pass "async-export-$engine_fn: no async 'pub fn $engine_fn' export"
    fi
done

echo ""

# =============================================================================
# Section 3: Type Export Smuggling Detection
# =============================================================================

echo "─ SCAN 2: Type Export Smuggling ─────────────────────────────────────────────"

for engine_fn in "${FORBIDDEN_EXPORTS[@]}"; do
    # Pattern: pub struct, pub enum, pub trait named after engine function
    SNAKE_CASE=$(echo "$engine_fn" | sed 's/_//g')
    PASCAL_CASE=$(echo "$engine_fn" | sed 's/_//g' | sed 's/\b\(.\)/\U\1/g')

    if grep -r "pub\s\+\(struct\|enum\|trait\)\s\+$PASCAL_CASE" "$COMPAT_SRC" 2>/dev/null | grep -v "// ALLOWED" > /dev/null; then
        fail "type-export-$engine_fn: found struct/enum/trait named '$PASCAL_CASE' (related to $engine_fn)"
        grep -r "pub\s\+\(struct\|enum\|trait\)\s\+$PASCAL_CASE" "$COMPAT_SRC" 2>/dev/null | sed 's/^/    > /'
    else
        pass "type-export-$engine_fn: no type export related to $engine_fn"
    fi
done

echo ""

# =============================================================================
# Section 4: WASM Export Bypass Detection
# =============================================================================

echo "─ SCAN 3: WASM Export Bypass Detection ──────────────────────────────────────"

for engine_fn in "${FORBIDDEN_EXPORTS[@]}"; do
    if grep -r "#\[export_name\s*=\s*\"$engine_fn\"" "$COMPAT_SRC" 2>/dev/null > /dev/null; then
        fail "wasm-export-bypass-$engine_fn: found #[export_name = \"$engine_fn\"] attribute"
        grep -r "#\[export_name\s*=\s*\"$engine_fn\"" "$COMPAT_SRC" 2>/dev/null | sed 's/^/    > /'
    else
        pass "wasm-export-bypass-$engine_fn: no #[export_name] bypass for $engine_fn"
    fi

    # Also check variations like #[wasm_bindgen(name = "...")]
    if grep -r "#\[wasm_bindgen.*name\s*=\s*\"$engine_fn\"" "$COMPAT_SRC" 2>/dev/null > /dev/null; then
        fail "wasm-bindgen-$engine_fn: found #[wasm_bindgen(name = \"$engine_fn\")] in source"
        grep -r "#\[wasm_bindgen.*name\s*=\s*\"$engine_fn\"" "$COMPAT_SRC" 2>/dev/null | sed 's/^/    > /'
    else
        pass "wasm-bindgen-$engine_fn: no #[wasm_bindgen] name override for $engine_fn"
    fi
done

echo ""

# =============================================================================
# Section 5: Trait Implementation Smuggling
# =============================================================================

echo "─ SCAN 4: Trait Implementation Smuggling ────────────────────────────────────"

for engine_fn in "${FORBIDDEN_EXPORTS[@]}"; do
    # Look for impl blocks that include engine function names
    if grep -r "impl.*{" "$COMPAT_SRC" -A 20 2>/dev/null | grep -E "fn\s+$engine_fn\s*\(" 2>/dev/null | grep -v "// ALLOWED" > /dev/null; then
        fail "impl-smuggling-$engine_fn: found '$engine_fn' in impl block"
        grep -r "impl.*{" "$COMPAT_SRC" -A 20 2>/dev/null | grep -B 5 "fn\s\+$engine_fn\s*\(" | sed 's/^/    > /'
    else
        pass "impl-smuggling-$engine_fn: no trait/impl smuggling of $engine_fn"
    fi
done

echo ""

# =============================================================================
# Section 6: Engine Dependency Smuggling (without graduation bridge)
# =============================================================================

echo "─ SCAN 5: Engine Dependency Analysis ────────────────────────────────────────"

# Check for "use engine::" or direct imports from wasm4pm-engine without graduation bridge
if grep -r "use.*engine::\|use.*wasm4pm_engine::" "$COMPAT_SRC" 2>/dev/null > /dev/null; then
    ENGINE_USES=$(grep -r "use.*engine::\|use.*wasm4pm_engine::" "$COMPAT_SRC" 2>/dev/null | wc -l)

    if [[ "$GRADUATION_BRIDGE_REQUIRED" == "true" ]]; then
        # Engine use is allowed ONLY if in graduation context
        GRADUATION_CONTEXT_COUNT=$(grep -r "use.*engine::" "$COMPAT_SRC" -B 5 -A 5 2>/dev/null | grep -c "GraduateToWasm4pm\|graduation\|#\[cfg(feature\s*=\s*\"wasm4pm\"" || echo 0)

        if [[ "$GRADUATION_CONTEXT_COUNT" -eq 0 && "$ENGINE_USES" -gt 0 ]]; then
            fail "engine-use-without-bridge: found $ENGINE_USES 'use engine::' without graduation context"
            grep -r "use.*engine::\|use.*wasm4pm_engine::" "$COMPAT_SRC" 2>/dev/null | sed 's/^/    > /'
        else
            pass "engine-use-gated: all engine imports are under graduation bridge context"
        fi
    else
        warn "engine-use-found: $ENGINE_USES 'use engine::' statements found (graduation not required)"
    fi
else
    pass "engine-use-none: no engine imports detected in source"
fi

echo ""

# =============================================================================
# Section 7: Graduation Bridge Verification (if wasm4pm feature enabled)
# =============================================================================

echo "─ SCAN 6: Graduation Bridge Verification ───────────────────────────────────"

# Check if wasm4pm feature or graduation bridge exists
if [[ -f "$COMPAT_SRC/graduation.rs" ]] || grep -r "GraduateToWasm4pm" "$COMPAT_SRC" 2>/dev/null > /dev/null; then
    info "graduation bridge detected"

    # Verify it's under a feature gate
    if grep -r "#\[cfg(feature\s*=\s*\"wasm4pm\"\s*)\]" "$COMPAT_SRC" 2>/dev/null > /dev/null; then
        pass "graduation-feature-gated: GraduateToWasm4pm is properly feature-gated"
    else
        warn "graduation-not-gated: GraduateToWasm4pm trait found but not under #[cfg(feature = \"wasm4pm\")]"
    fi
else
    info "no graduation bridge detected (may be intentional if wasm4pm feature not enabled)"
fi

echo ""

# =============================================================================
# Section 8: Generated Artifacts Scan (if present)
# =============================================================================

echo "─ SCAN 7: Generated Artifacts Analysis ──────────────────────────────────────"

if [[ -d "$COMPAT_GENERATED" ]]; then
    info "scanning generated artifacts at $COMPAT_GENERATED"

    for engine_fn in "${FORBIDDEN_EXPORTS[@]}"; do
        if find "$COMPAT_GENERATED" -type f \( -name "*.rs" -o -name "*.wit" -o -name "*.ts" \) 2>/dev/null | \
           xargs grep -l "pub\s\+fn\s\+$engine_fn\|export.*$engine_fn" 2>/dev/null | wc -l | grep -qv "^0$"; then
            fail "generated-export-$engine_fn: found '$engine_fn' in generated artifacts"
        else
            pass "generated-export-$engine_fn: no $engine_fn in generated code"
        fi
    done
else
    info "generated artifacts directory not found (may not have been built yet): $COMPAT_GENERATED"
fi

echo ""

# =============================================================================
# Section 9: WIT Surface Validation (if present)
# =============================================================================

echo "─ SCAN 8: WIT Surface Validation ───────────────────────────────────────────"

WIT_FILES=$(find "$REPO_ROOT" -name "*.wit" 2>/dev/null | head -10)
if [[ -n "$WIT_FILES" ]]; then
    info "found WIT files, checking for engine functions"

    for engine_fn in "${FORBIDDEN_EXPORTS[@]}"; do
        if echo "$WIT_FILES" | xargs grep -l "fn $engine_fn\|export.*$engine_fn" 2>/dev/null | wc -l | grep -qv "^0$"; then
            fail "wit-export-$engine_fn: found '$engine_fn' in WIT interface definition"
        else
            pass "wit-export-$engine_fn: no $engine_fn exported in WIT"
        fi
    done
else
    info "no WIT files found (expected if not a WASM component project)"
fi

echo ""

# =============================================================================
# Section 10: Cargo.toml Feature Analysis
# =============================================================================

echo "─ SCAN 9: Feature Configuration ─────────────────────────────────────────────"

CARGO_TOML="$REPO_ROOT/Cargo.toml"
if [[ -f "$CARGO_TOML" ]]; then
    # Check for suspicious features that might enable engine functions
    if grep -q "wasm4pm.*engine\|engine.*execution" "$CARGO_TOML"; then
        warn "cargo-feature: found 'wasm4pm' or 'engine' in Cargo.toml features"
    fi

    # Verify allowed features
    if grep -q "\[features\]" "$CARGO_TOML"; then
        DECLARED_FEATURES=$(grep -A 20 "\[features\]" "$CARGO_TOML" | grep "^[a-z]" | cut -d' ' -f1 | tr -d '"')
        info "declared features: $DECLARED_FEATURES"

        # Features should be: formats, strict, wasm4pm (not engine-specific)
        SUSPICIOUS_FEATURES=$(echo "$DECLARED_FEATURES" | grep -E "engine|mining|conformance|replay|alignment" || echo "")
        if [[ -n "$SUSPICIOUS_FEATURES" ]]; then
            fail "cargo-suspicious-features: found suspicious features: $SUSPICIOUS_FEATURES"
        else
            pass "cargo-features-clean: no engine-specific features in Cargo.toml"
        fi
    fi
else
    fail "cargo-toml-missing: Cargo.toml not found at $CARGO_TOML"
fi

echo ""

# =============================================================================
# Section 11: Summary and Exit
# =============================================================================

echo "╔════════════════════════════════════════════════════════════════════════════╗"
TOTAL_CHECKS=$(( PASS_COUNT + FAIL_COUNT + WARN_COUNT ))
echo "║  AUDIT COMPLETE                                                          ║"
echo "║  Checks: $TOTAL_CHECKS  |  PASS: $PASS_COUNT  |  FAIL: $FAIL_COUNT  |  WARN: $WARN_COUNT"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

if [[ "$FAIL_COUNT" -gt 0 ]]; then
    echo "❌ AUDIT FAILED: $FAIL_COUNT violation(s) found"
    echo ""
    echo "REFUSAL REASON: execution-smuggling"
    echo "DOCTRINE: Engine functions (mining, conformance, replay, alignment, receipting,"
    echo "          benchmarking) MUST NOT be exported from wasm4pm-compat."
    echo ""
    echo "ALLOWED PATHS:"
    echo "  1. GraduateToWasm4pm trait (under #[cfg(feature = \"wasm4pm\")])"
    echo "  2. External wasm4pm dependency (once stabilized)"
    echo "  3. Explicit engine crate import (wasm4pm-engine or similar)"
    echo ""
    exit 1
elif [[ "$WARN_COUNT" -gt 0 ]]; then
    echo "⚠️  AUDIT PASSED WITH WARNINGS: $WARN_COUNT warning(s)"
    echo "    Review WARN lines above for potential issues."
    exit 0
else
    echo "✅ AUDIT PASSED: All checks clear"
    echo "   No forbidden engine exports detected."
    echo "   Compat layer is clean and graduation-ready."
    exit 0
fi
