#!/usr/bin/env bash
# audit-script.tera: Renders a bash audit script for a SourceModule ontology instance.
# Constitutional Equation: audit/<moduleName>.sh = mu(wasm4pm-compat.ttl, SourceModule)
#
# Input variables:
#   moduleName           — snake_case module name, e.g. "ocel"
#   sourceFile           — relative path, e.g. "src/ocel.rs"
#   rustType             — primary Rust type name, e.g. "OcelLog"
#   graduatesToWasm4pm   — boolean, true if this module graduates
#   laws                 — array of law names this module must satisfy
#
# Auto-generated by ggen from wasm4pm-compat.ttl --- DO NOT EDIT
# Source: wasm4pm-compat.ttl  (SourceModule: process_cube)
# Regenerate with: ggen sync --template audit-script.teraset -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PASS_COUNT=0
FAIL_COUNT=0

pass() { echo "PASS  $1"; (( PASS_COUNT += 1 )); }
fail() { echo "FAIL  $1"; (( FAIL_COUNT += 1 )); }

echo "=== Audit: process_cube (process_cube) ==="
echo "    Source: src/process_cube.rs"
echo ""

# -------------------------------------------------------------------------
# CHECK 1: Source module exists
# -------------------------------------------------------------------------
if [[ -f "${REPO_ROOT}/src/process_cube.rs" ]]; then
    pass "module-exists: src/process_cube.rs is present"
else
    fail "module-exists: src/process_cube.rs is MISSING"
fi

# -------------------------------------------------------------------------
# CHECK 2: Module is declared in src/lib.rs (or appropriate root)
# -------------------------------------------------------------------------
if grep -q "mod process_cube" "${REPO_ROOT}/src/lib.rs" 2>/dev/null; then
    pass "module-declared: 'process_cube' found in src/lib.rs"
else
    fail "module-declared: 'process_cube' NOT found in src/lib.rs"
fi

# -------------------------------------------------------------------------
# CHECK 3: At least one compile-pass fixture covers this module
# -------------------------------------------------------------------------
PASS_FIXTURES=$(find "${REPO_ROOT}/tests/ui/compile_pass" -name "*.rs" \
    -exec grep -l "process_cube\|process_cube" {} \; 2>/dev/null | wc -l | tr -d ' ')
if [[ "${PASS_FIXTURES}" -ge 1 ]]; then
    pass "pass-fixture-exists: ${PASS_FIXTURES} compile-pass fixture(s) cover process_cube"
else
    fail "pass-fixture-exists: no compile-pass fixture found for process_cube"
fi

# -------------------------------------------------------------------------
# CHECK 4: At least one compile-fail fixture per declared law
# -------------------------------------------------------------------------


echo "INFO  no laws declared for process_cube — skipping per-law fixture check"


# -------------------------------------------------------------------------
# CHECK 5: Rustdoc present (module-level //! comment)
# -------------------------------------------------------------------------
if grep -q "^//!" "${REPO_ROOT}/src/process_cube.rs" 2>/dev/null; then
    pass "rustdoc-present: //! comment found in src/process_cube.rs"
else
    fail "rustdoc-present: no //! module-level doc in src/process_cube.rs"
fi

# -------------------------------------------------------------------------
# CHECK 6: Graduation marker (if graduatesToWasm4pm)
# -------------------------------------------------------------------------

echo "INFO  process_cube does not graduate to wasm4pm — skipping graduation check"


# -------------------------------------------------------------------------
# CHECK 7: No forbidden patterns
# -------------------------------------------------------------------------
if grep -qE "unsafe\s*\{" "${REPO_ROOT}/src/process_cube.rs" 2>/dev/null; then
    fail "no-unsafe: unsafe block found in src/process_cube.rs — violates #![forbid(unsafe_code)]"
else
    pass "no-unsafe: no unsafe blocks in src/process_cube.rs"
fi

if grep -q "InvalidInput" "${REPO_ROOT}/src/process_cube.rs" 2>/dev/null; then
    fail "no-bare-refusal: 'InvalidInput' found in src/process_cube.rs — refusals must carry named laws"
else
    pass "no-bare-refusal: no bare InvalidInput in src/process_cube.rs"
fi

# -------------------------------------------------------------------------
# SUMMARY
# -------------------------------------------------------------------------
echo ""
echo "=== process_cube audit complete: ${PASS_COUNT} PASS, ${FAIL_COUNT} FAIL ==="

if [[ "${FAIL_COUNT}" -gt 0 ]]; then
    exit 1
fi